service: twitch-stitch-infra

provider:
  name: aws
  profile: serverless-admin
  region: us-west-1
  runtime: python3.6
  stackName: sls-twitch-stitch-infra
  stage: dev
  versionFunctions: false

package:
  individually: true
  exclude:
    - '*/**'

custom:
  pythonRequirements:
    dockerizePip: non-linux
    dockerSsh: true

resources:
  - ${file(./config/databases.yml)}
  - ${file(./config/queues.yml)}
