service: ts-infra

provider:
  name: aws
  profile: serverless-admin
  region: ${self:custom.config.region}
  runtime: python3.7
  stage: ${self:custom.config.stage}
  versionFunctions: false
  environment:
    TS_ENV: ${self:custom.config.stage}

  vpc:
    securityGroupIds:
      - "Fn::GetAtt": [VPC, DefaultSecurityGroup]
    subnetIds:
      - Ref: SubnetLambdaA
      - Ref: SubnetLambdaB
      - Ref: SubnetLambdaC
  iamRoleStatements:
    ${self:custom.config.iam.role-statement}

  memorySize: 128
  timeout: 30

package:
  exclude:
    - '*/**'
  include:
    - modules/**/run.py

plugins:
  - serverless-python-requirements

custom:
  config: ${file(../ts_shared/ts_config/ts_config/ts_config_${opt:stage, 'dev'}.yml)}
  pythonRequirements:
    dockerizePip: non-linux
    dockerSsh: true
    slim: true

resources:
  - ${file(./config/vpc.yml)}
  - ${file(./config/subnet.yml)}
  - ${file(./config/rds.yml)}
  - ${file(./config/ec2.yml)}
  - ${file(./config/queue.yml)}
  - ${file(./config/cognito.yml)}
  - ${file(./config/output.yml)}

functions:
  infra--user--presignup:
    handler: modules/user__presignup/run.run
    events:
      - cognitoUserPool:
          pool: UserPool
          trigger: PreSignUp
