service: ts-infra

provider:
  name: aws
  profile: serverless-admin
  region: ${self:custom.config.aws.region}
  runtime: python3.6
  stage: dev
  versionFunctions: false

package:
  individually: true
  exclude:
    - '*/**'

plugins:
  - serverless-dynamodb-autoscaling

custom:
  config: ${file(../ts_shared/ts_config/ts_config/ts_config.yml)}
  capacities:
    ${file(./config/capacities.yml)}

resources:
  - ${file(./config/databases.yml)}
  - ${file(./config/queues.yml)}
