service: ts-infra

provider:
  name: aws
  profile: serverless-admin
  region: us-west-1
  runtime: python3.6
  stage: dev
  versionFunctions: false

package:
  individually: true
  exclude:
    - '*/**'

plugins:
  - serverless-dynamodb-autoscaling

custom:
  capacities:
    ${file(./config/capacities.yml)}

resources:
  - ${file(./config/databases.yml)}
  - ${file(./config/queues.yml)}
