- table: StreamTable
  read:
    minimum: 5
    maximum: 500
    usage: 0.75
  write:
    minimum: 5
    maximum: 500
    usage: 0.75
- table: StreamSegmentsTable
  read:
    minimum: 15
    maximum: 1000
    usage: 0.75
  write:
    minimum: 15
    maximum: 1000
    usage: 0.75
- table: ClipTable
  read:
    minimum: 5
    maximum: 500
    usage: 0.75
  write:
    minimum: 5
    maximum: 500
    usage: 0.75
- table: ClipSegmentsTable
  read:
    minimum: 15
    maximum: 1000
    usage: 0.75
  write:
    minimum: 15
    maximum: 1000
    usage: 0.75
- table: MontageTable
  read:
    minimum: 5
    maximum: 500
    usage: 0.75
  write:
    minimum: 5
    maximum: 500
    usage: 0.75
- table: MontageClipsTable
  read:
    minimum: 5
    maximum: 500
    usage: 0.75
  write:
    minimum: 5
    maximum: 500
    usage: 0.75
