- table: StreamsTable
  read:
    minimum: 5
    maximum: 500
    usage: 0.75
  write:
    minimum: 5
    maximum: 500
    usage: 0.75
- table: StreamMomentsTable
  read:
    minimum: 5
    maximum: 500
    usage: 0.75
  write:
    minimum: 5
    maximum: 500
    usage: 0.75
- table: StreamSegmentsTable
  read:
    minimum: 150
    maximum: 1000
    usage: 0.75
  write:
    minimum: 250
    maximum: 1000
    usage: 0.75
- table: ClipsTable
  read:
    minimum: 5
    maximum: 500
    usage: 0.75
  write:
    minimum: 5
    maximum: 500
    usage: 0.75
- table: ClipSegmentsTable
  read:
    minimum: 5
    maximum: 500
    usage: 0.75
  write:
    minimum: 5
    maximum: 500
    usage: 0.75
- table: MontagesTable
  read:
    minimum: 5
    maximum: 500
    usage: 0.75
  write:
    minimum: 5
    maximum: 500
    usage: 0.75
- table: MontageClipsTable
  read:
    minimum: 5
    maximum: 500
    usage: 0.75
  write:
    minimum: 5
    maximum: 500
    usage: 0.75
