- table: StreamTable
  read:
    minimum: 1
    maximum: 10
    usage: 0.75
  write:
    minimum: 1
    maximum: 10
    usage: 0.75
- table: StreamSegmentsTable
  read:
    minimum: 5
    maximum: 25
    usage: 0.75
  write:
    minimum: 5
    maximum: 25
    usage: 0.75
- table: ClipTable
  read:
    minimum: 1
    maximum: 10
    usage: 0.75
  write:
    minimum: 1
    maximum: 10
    usage: 0.75
- table: ClipSegmentsTable
  read:
    minimum: 5
    maximum: 25
    usage: 0.75
  write:
    minimum: 5
    maximum: 25
    usage: 0.75
- table: MontageTable
  read:
    minimum: 1
    maximum: 10
    usage: 0.75
  write:
    minimum: 1
    maximum: 10
    usage: 0.75
- table: MontageClipsTable
  read:
    minimum: 1
    maximum: 10
    usage: 0.75
  write:
    minimum: 1
    maximum: 10
    usage: 0.75
