Resources:

  CognitoUserPoolUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: twitch-stitch-user-pool-${self:custom.config.stage}
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: twitch-stitch-user-pool-client-${self:custom.config.stage}
      UserPoolId:
        Ref: CognitoUserPoolUserPool
