Resources:
  ClipDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.clip.name}-dead

  ClipQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.clip.name}
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - ClipDeadQueue
            - Arn
        maxReceiveCount: 100

  MontageDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.montage.name}-dead

  MontageQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.montage.name}
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - MontageDeadQueue
            - Arn
        maxReceiveCount: 100

  StreamAnalyzeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.stream--analyze.name}
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - StreamAnalyzeDeadQueue
            - Arn
        maxReceiveCount: 100

  StreamAnalyzeDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.stream--analyze.name}-dead

  StreamInitializeDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.stream--initialize.name}-dead

  StreamInitializeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.stream--initialize.name}
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - StreamInitializeDeadQueue
            - Arn
        maxReceiveCount: 100

  StreamSegmentAnalyzeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.stream-segment--analyze.name}
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - StreamSegmentAnalyzeDeadQueue
            - Arn
        maxReceiveCount: 100

  StreamSegmentAnalyzeDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.stream-segment--analyze.name}-dead

  StreamSegmentDownloadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.stream-segment--download.name}
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - StreamSegmentDownloadDeadQueue
            - Arn
        maxReceiveCount: 100

  StreamSegmentDownloadDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.stream-segment--download.name}-dead
