Resources:
  ClipDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.clip.name}-dead-${self:custom.config.stage}

  ClipQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.clip.name}-${self:custom.config.stage}
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt": [ClipDeadQueue, Arn]
        maxReceiveCount: 1000

  MontageDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.montage.name}-dead-${self:custom.config.stage}

  MontageQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.montage.name}-${self:custom.config.stage}
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt": [MontageDeadQueue, Arn]
        maxReceiveCount: 1000

  StreamAnalyzeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream--analyze.name}-${self:custom.config.stage}
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt": [StreamAnalyzeDeadQueue, Arn]
        maxReceiveCount: 1000

  StreamAnalyzeDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream--analyze.name}-dead-${self:custom.config.stage}

  StreamInitializeDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream--initialize.name}-dead-${self:custom.config.stage}

  StreamInitializeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream--initialize.name}-${self:custom.config.stage}
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt": [StreamInitializeDeadQueue, Arn]
        maxReceiveCount: 1000

  StreamSegmentAnalyzeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream-segment--analyze.name}-${self:custom.config.stage}
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt": [StreamSegmentAnalyzeDeadQueue, Arn]
        maxReceiveCount: 1000

  StreamSegmentAnalyzeDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream-segment--analyze.name}-dead-${self:custom.config.stage}

  StreamSegmentDownloadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream-segment--download.name}-${self:custom.config.stage}
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt": [StreamSegmentDownloadDeadQueue, Arn]
        maxReceiveCount: 1000

  StreamSegmentDownloadDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream-segment--download.name}-dead-${self:custom.config.stage}
