Resources:

  ClipQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.clip.name}
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt": [ClipDeadQueue, Arn]
        maxReceiveCount: 1000

  ClipDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.clip.name}---dead

  MontageQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.montage.name}
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt": [MontageDeadQueue, Arn]
        maxReceiveCount: 1000

  MontageDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.montage.name}---dead

  StreamAnalyzeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream--analyze.name}
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt": [StreamAnalyzeDeadQueue, Arn]
        maxReceiveCount: 1000

  StreamAnalyzeDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream--analyze.name}---dead

  StreamInitializeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream--initialize.name}
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt": [StreamInitializeDeadQueue, Arn]
        maxReceiveCount: 1000

  StreamInitializeDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream--initialize.name}---dead

  StreamSegmentAnalyzeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream-segment--analyze.name}
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt": [StreamSegmentAnalyzeDeadQueue, Arn]
        maxReceiveCount: 1000

  StreamSegmentAnalyzeDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream-segment--analyze.name}---dead

  StreamSegmentDownloadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream-segment--download.name}
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt": [StreamSegmentDownloadDeadQueue, Arn]
        maxReceiveCount: 1000

  StreamSegmentDownloadDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream-segment--download.name}---dead
