Resources:
  ClipDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ts-clip-dead

  ClipQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ts-clip
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - ClipDeadQueue
            - Arn
        maxReceiveCount: 10

  StreamInitializeDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ts-stream-initialize-dead

  StreamInitializeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ts-stream-initialize
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - StreamInitializeDeadQueue
            - Arn
        maxReceiveCount: 10

  StreamSegmentDownloadDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ts-stream-segment-download-dead

  StreamSegmentDownloadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ts-stream-segment-download
      VisibilityTimeout: 180
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - StreamSegmentDownloadDeadQueue
            - Arn
        maxReceiveCount: 10
