Resources:
  ClipDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.clip.name}-dead

  ClipQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.clip.name}
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - ClipDeadQueue
            - Arn
        maxReceiveCount: 10

  StreamInitializeDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.stream-initialize.name}-dead

  StreamInitializeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.stream-initialize.name}
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - StreamInitializeDeadQueue
            - Arn
        maxReceiveCount: 10

  StreamSegmentDownloadDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.stream-segment-download.name}-dead

  StreamSegmentDownloadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.aws.sqs.stream-segment-download.name}
      VisibilityTimeout: 180
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - StreamSegmentDownloadDeadQueue
            - Arn
        maxReceiveCount: 10
