Resources:

  ClipQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.clip.name}-${self:custom.config.stage}
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn:
          Ref: ClipDeadQueue
        maxReceiveCount: 1000

  ClipDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.clip.name}-dead-${self:custom.config.stage}

  MontageQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.montage.name}-${self:custom.config.stage}
      VisibilityTimeout: 30
      RedrivePolicy:
        deadLetterTargetArn:
          Ref: MontageDeadQueue
        maxReceiveCount: 1000

  MontageDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.montage.name}-dead-${self:custom.config.stage}

  StreamAnalyzeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream--analyze.name}-${self:custom.config.stage}
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          Ref: StreamAnalyzeDeadQueue
        maxReceiveCount: 1000

  StreamAnalyzeDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream--analyze.name}-dead-${self:custom.config.stage}

  StreamInitializeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream--initialize.name}-${self:custom.config.stage}
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          Ref: StreamInitializeDeadQueue
        maxReceiveCount: 1000

  StreamInitializeDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream--initialize.name}-dead-${self:custom.config.stage}

  StreamSegmentAnalyzeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream-segment--analyze.name}-${self:custom.config.stage}
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          Ref: StreamSegmentAnalyzeDeadQueue
        maxReceiveCount: 1000

  StreamSegmentAnalyzeDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream-segment--analyze.name}-dead-${self:custom.config.stage}

  StreamSegmentDownloadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream-segment--download.name}-${self:custom.config.stage}
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          Ref: StreamSegmentDownloadDeadQueue
        maxReceiveCount: 1000

  StreamSegmentDownloadDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.config.sqs.queues.stream-segment--download.name}-dead-${self:custom.config.stage}
