Resources:

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DBSubnetGroup
      SubnetIds:
      - Ref: SubnetRDSA
      - Ref: SubnetRDSB
      - Ref: SubnetRDSC

  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: DBClusterParameterGroup
      Family: aurora5.6
      Parameters:
        character_set_client: utf8
        character_set_database: utf8
        character_set_results: utf8
        character_set_connection: utf8
        collation_connection: utf8_unicode_ci
        collation_server: utf8_unicode_ci
        character_set_server: utf8

  DBCluster:
    # DependsOn: VPC
    Type: AWS::RDS::DBCluster
    Properties:
      VpcSecurityGroupIds:
        - "Fn::GetAtt": [VPC, DefaultSecurityGroup]
      DBSubnetGroupName:
        Ref: DBSubnetGroup
      DBClusterParameterGroupName:
        Ref: DBClusterParameterGroup
      Engine: aurora
      EngineMode: serverless
      DBClusterIdentifier: twitch-stitch-${self:custom.config.stage}
      DatabaseName: ${self:custom.config.rds.db}
      MasterUsername: ${self:custom.config.rds.username}
      MasterUserPassword: ${self:custom.config.rds.password}
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 64
        MinCapacity: 2
        SecondsUntilAutoPause: 300
      BackupRetentionPeriod: 7

