Resources:

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      VPCSecurityGroups:
      - "Fn::GetAtt": [VPC, DefaultSecurityGroup]
      DBSubnetGroupName:
        Ref: DBSubnetGroup
      DBParameterGroupName:
        Ref: DBParameterGroup
      DBInstanceIdentifier: twitch-stitch-${self:custom.config.stage}
      DBName: ${self:custom.config.rds.db}
      MasterUsername: ${self:custom.config.rds.username}
      MasterUserPassword: ${self:custom.config.rds.password}
      Engine: mysql
      EngineVersion: 5.6.40
      DBInstanceClass: db.t3.medium
      StorageType: gp2
      AllocatedStorage: 20
      MultiAZ: false
      PubliclyAccessible: true
      BackupRetentionPeriod: 7

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DBSubnetGroup
      SubnetIds:
      - Ref: SubnetRDSA
      - Ref: SubnetRDSB

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: DBParameterGroup
      Family: mysql5.6
      Parameters:
        character_set_client: utf8
        character_set_database: utf8
        character_set_results: utf8
        character_set_connection: utf8
        collation_connection: utf8_unicode_ci
        collation_server: utf8_unicode_ci
        character_set_server: utf8
        max_connections: 2000
